version: '3.3'    
services:
  covid_api:
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    ports:
      - "8080:9001"
    environment:
      NODE_ENV: "production"
      LOG_LEVEL: "error"
      SERVER_PORT: "9001"
      ACCESS_TOKEN_SECRET: "1234"
    depends_on:
      - db
  db:
    image: "postgres"
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=covid
    volumes:
      - ./../db/postgres/data:/var/lib/postgresql/data/
  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080
